### ISSUE TITLE
Error: replacement has length zero with test samples

### ISSUE THREAD

**Issue by jason2389** [fallerlab/ARF#4]
Hello, 
I am running the script with the test samples and I am getting this error:

preparing geneSet collections...
GSEA analysis...
leading edge analysis...
done...
Error in x[[jj]][iseq] <- vjj : replacement has length zero

R version 4.2.1

Thanks for your help!

**Comment by ferhatalkan** [comment]
Hi, sorry to hear about the issue. Can you specify in which function do you get the error?  If possible, can you copy/paste the exact command as well?

**Comment by jason2389** [comment]
I get the error after the the leading edge analysis

GSEA analysis...
leading edge analysis...
done...
Error in x[[jj]][iseq] <- vjj : replacement has length zero

dripARF_results <- ARF::dripARF(samplesFile = "Rpl10aRps25Rpl22_samples_mouse.tsv", organism="mm", QCplot=TRUE, targetDir="dripARF_results/")

Thanks!

**Comment by ferhatalkan** [comment]
Just figured out the reason, it is because of clusterProfiler::GSEA function now returns a column with ID "qvalue" not "qvalues" as ARF expecting. I can release a fix accepting both ids, but, Can you let me know which version of clusterProfiler you are using so that I can make sure this is the problem?

**Comment by ferhatalkan** [comment]
Also the version of DOSE package?

**Comment by jason2389** [comment]
That would be great if you could release an updated version!

DOSE package : 3.22.1
clusterProfiler : 4.4.4

**Comment by ferhatalkan** [comment]
If you don't want to wait for the new release (I need to do some tests etc. , so,  it might take a bit since I'm adding a few other fixes), you can clone the git repository to your local machine,  change the "qvalues" to "qvalue" at line  440, 450 and 1060 within ARF_platform.R script and install from your updated repository. Let me know if that works :)

**Comment by ferhatalkan** [comment]
The change at line 440 might not be needed though.

**Comment by jason2389** [comment]
Thanks for the info. I have created a branch and did the changes you suggested. Now it works! Many thanks!

**Comment by nayanvs** [comment]
I used the cloned version to avoid qvalues errors with the test data but ran into another error with it. Waiting for the new release.

No id variables; using all as measure variables
Error in base::nchar(wide_chars$test, type = "width") : 
  lazy-load database '/usr/local/lib/R/site-library/cli/R/sysdata.rdb' is corrupt
In addition: Warning message:
In base::nchar(wide_chars$test, type = "width") :
  internal error -3 in R_decompress1

**Comment by ferhatalkan** [comment]
This looks more like a package installation error. Also seems like it comes from another package, not from ARF.
